name: progettino-dev
services:
  web:
    container_name: progettino-dev
    image: node:slim
    working_dir: /app
    volumes:
      - .:/app # Monta il codice del progetto direttamente nel container
      - /app/node_modules # Evita problemi di dipendenze
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    restart: always
    environment:
      - NODE_ENV=development
